### PR TITLE
Pr/dynamic

### PR DESCRIPTION
**Pull request by JakeGinnivan**
Replaces #269 

This is #269 rebased plus fixed the test so it runs all the time and not against remote repo

### CODE REVIEW

**Comment by dazinator** [comment]
@JakeGinnivan 
When I ran this, after the following line:
image

I checked the _dynamicrepository directory expecting to see a .git repo.

Instead I see an empty folder:

image

Is this correct? I was kind of expecting to see my git repo located there!

**Comment by JakeGinnivan** [comment]
@GeertvanHorrik help! :)

**Comment by JakeGinnivan** [comment]
@dazinator do you have hidden folders turned on? the .git folder could be hidden. The code says not to check anything out

**Comment by dazinator** [comment]
Ah gees - I am using a new laptop today - and yes.. do not show hidden files is turned on.

Damn you Windows!

*Hits self on head with large object*

image

**Comment by dazinator** [comment]
Cool - this seems to be running well based on my own local testing. I have not tried plugging it in to a team city build yet, I'm curious to know if it will allow the checkout on agent scenario. I will try that next. Cheers Guys!

**Comment by GeertvanHorrik** [comment]
We do a bare clone (not a checkout since we don't need that). That means that you only have the hidden .git folder. For another project, GitLink, I have created this:

https://github.com/CatenaLogic/GitLink/blob/develop/src/GitLink/TemporaryFilesContext.cs

Maybe good to copy/paste to ensure the removing of temporary files? Or are they already being deleted? (I am not sure, done so many projects I simply forgot).

**Comment by dazinator** [comment]
@JakeGinnivan @GeertvanHorrik  - I found a problem.

Because we don't checkout the repo - the files don't exist on disk. This includes the "NextVersion.txt" file which GitVersion expects to be on disk in the repo directory - so it won't ever find that file at the moment! 

I'm not that familiar with Git (as you well know) - would it be possible to query the git repo to see if has such a file and then if it does, check it out? I think that's the only bit that's missing.

**Comment by SimonCropp** [comment]
ok going merge this. @dazinator can u raise a new issue for the nextversion issue and we will work on that separately.

**Comment by GeertvanHorrik** [comment]
It should be supported, see https://github.com/ParticularLabs/GitVersion/blob/ca002ed570b03f2f3a610523ab79adf34848fdc1/GitVersionExe/GitPreparer.cs#L105

**Comment by dazinator** [comment]
Thanks @GeertvanHorrik - from looking at that code - it seems that nextversion txt checkout only happens if you pass in a targetbranch argument - which I'm not doing so that may explain it. I'll raise a seperate issue

**Comment by SimonCropp** [comment]
@dazinator thanks

**Comment by SimonCropp** [comment]
@dazinator thanks

**Pull request merged**
