### PR TITLE
Updated libgit2sharp

### PR DESCRIPTION
**Pull request by GeertvanHorrik**
Quite a few breaking changes, and I needed to do this anyway because of https://github.com/libgit2/libgit2sharp/issues/993 to check if it is fixed in the latest version.

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
I don't want to take anything into v2.x if at all possible. Lots has changed in the v3 branch and this would likley conflict quite badly. Any chance you could look at applying to the `release/3.0.0` branch?

@andreasohlund how is the testing of v3 going? Can we merge it into master yet?

**Comment by GeertvanHorrik** [comment]
I wasn't sure, I didn't want to introduce this into v3 (because I know it's beta / RC). But no problem, I can do that. Just give me the signal if you want to.

**Comment by JakeGinnivan** [comment]
Basically as far as I am concerned v3 is done. Need people to verify it still works fine for then before releasing it. 

I am not going to merge this as looking through the changes it would be merge hell for me when I need to merge v3 into master :P 

If you can test v3 as well then that would be super handy, there was so much changed I wanted a few people to verify before releasing stable

**Comment by gep13** [comment]
For what's is worth...

I have been using v3 in the ChocolateyGUI build process for the last few weeks, and it has been working great :+1:

**Comment by andreasohlund** [comment]
I'd say we're good to go

**Comment by JakeGinnivan** [comment]
There is a failing test on 3.0.0 branch. Lets fix and merge/release sometime this week/weekend?

**Comment by nulltoken** [comment]
Would you be willing to go with a pre-release version of LibGit2Sharp, I'd suggest you to move to https://www.nuget.org/packages/LibGit2Sharp/0.22.0-pre20150317225305

There are a ton of breaking changes in this one that you may be willing to cope with sooner rather than later. As usual, ping me would you need any help, I'll be happy to give a hand.

**Pull request closed without merging**
