### PR TITLE
Use defined project intermediate directory if it exists

### LINKED ISSUE #332: Defined project intermediate directory is not respected
Fix for #146  causes a directory in $(ProjectDir)\obj\$(Configuration) to be created, even if the project has specified a different intermediate output directory.

I believe the value of $(IntermediateOutputPath) should be respected if it exists (which it does by default in VS projects).

### PR DESCRIPTION
**Pull request by bdhess**
Fixes #332

### CODE REVIEW

**Comment by gep13** [comment]
@SimonCropp when you have a second, can you take a look at this one?  Thanks!

**Comment by bdhess** [comment]
Sorry about that, and for the delay getting back to this.
@grufffta @SimonCropp - ready for another look?  The build appears to be clean now.  And thanks!

**Comment by JakeGinnivan** [comment]
This looks ok to me, but looks like a breaking change. @SimonCropp thoughts?

**Comment by SimonCropp** [comment]
Yeah in the strict sense this is breaking change

**Comment by JakeGinnivan** [comment]
Do we care?

Should we take this into v3 which has the config changes and other breaking stuff. Or just merge and put into next minor release?

**Comment by SimonCropp** [comment]
i think next minor is OK. i doubt many people are using the task on its own. and even if they do it will fail at buid time

**Pull request merged**
