### PR TITLE
Fix stale dynamic repo

### LINKED ISSUE #418: Stale dynamic repo cache
In 3.0.0-beta0002 it looks like caching for the dynamic repository was added, but that cache is never updated over time and becomes stale. As an example when new tags are added in the remote, GitVersion doesn't seem to see them in it's cached copy of the repository and we needed to manually delete the dynamic repo cache first to get a correct version number result.

I'm guessing it's related to this: https://github.com/ParticularLabs/GitVersion/pull/399#discussion-diff-26903087 but I haven't had a chance to investigate further yet.

### PR DESCRIPTION
**Pull request by JakeGinnivan**
Fixes  #418

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
@GeertvanHorrik would be good if you had a look at this one

**Comment by JakeGinnivan** [comment]
Bump @GeertvanHorrik or @gep13 ?

**Comment by gep13** [comment]
Sorry not been around lately, loads on! :-(

This looks good to me though.

**Comment by GeertvanHorrik** [comment]
Same to me, busy as hell. Will review tomorrow. Ping me if I forgot.

**Comment by GeertvanHorrik** [comment]
Looks good to me. I was wondering why the hard reset, but that's probably for the assemblyinfo update feature.

**Comment by JakeGinnivan** [comment]
@GeertvanHorrik hard reset is easier than doing a FF merge it seemed

**Pull request merged**
