### PR TITLE
fixes #101 fixes #336

### LINKED ISSUE #336: Dynamic Repository with GitHubFlow throws an exception
I am testing the Dynamic Repository functionality in combination with GitHubFlow and the latest release of GitVersion 2.0.0

From the command line:
gitversion /url https://stash.test.nl/customer/project/repo.git /b feature-TOHISP-91 /u user /p passw

Result:

  Trying to check out 'NextVersion.txt'
Working directory: D:\test\_dynamicrepository
Running against branch: feature-TOHISP-91
GitHubFlow version strategy will be used
An unexpected error occurred:
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at GitVersion.NextVersionTxtFileFinder.TryGetNextVersion(SemanticVersion& semanticVersion) in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionCore\GitHubFlow\NextVersionTxtFileFinder.cs:line 19
   at GitVersion.NextSemverCalculator.<GetPossibleVersions>d__2.MoveNext() in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionCore\GitHubFlow\NextSemverCalculator.cs:line 62
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitVersion.BuildNumberCalculator.GetBuildNumber(GitVersionContext context) in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionCore\GitHubFlow\BuildNumberCalculator.cs:line 26
   at GitVersion.Program.Run()

It fails at:
        public bool TryGetNextVersion(out SemanticVersion semanticVersion)
        {
            var filePath = Path.Combine(repositoryDirectory, "NextVersion.txt");

The repositoryDirectory is equal to null. The reason seems to be that the dynamic repository is a bare repository. This variable is set earlier on to:
context.Repository.Info.WorkingDirectory 

WorkingDirectory is part of LibGit2Sharp.

From their code:
        /// <summary>
        /// Gets the normalized path to the working directory.
        /// <para>
        ///   If the repository is bare, null is returned.
        /// </para>
        /// </summary>
        public virtual string WorkingDirectory { get; private set; }

Is this a known issue?

### PR DESCRIPTION
**Pull request by dazinator**
- Committed @MacDennis76 's fix which allows dynamic repository to run.. Although have no idea if this is an acceptable fix.

### CODE REVIEW

**Comment by gep13** [comment]
@andreasohlund @SimonCropp @distantcam 

Can you guys help with the build machine:

image

This PR failing the build seems to have nothing to do with the actual PR changes.

**Comment by gep13** [comment]
@dazinator can you walk me through what tests you did to verify this change?  Just want to be sure that we are on the same page, and if we can add some Unit/Integration Tests to cover this.

**Comment by dazinator** [comment]
Hi @gep13  

Certainly!

First I verified that there is an issue by simply running GitVersion.exe with the debugger attached, passing in the necessary arguments, something like /url /u and /p which relate to the repo url and github username and password. I stepped through the code until it blew up. The exception was to do with the fact that the repo object doesn't have a "working directory" and the class responsible for finding the `NextVersion.txt` file, uses the working directory of the repo - which was null - causing an exception.

I commented on #101 to that effect, and was prepared to leave it at that but then I noticed #336 which was reporting the same problem. More specifically, I noticed @MacDennis76 suggestion which was this one liner code change.

As I didn't see a PR for this change, I made this change locally, ran GitVersion.exe with the debugger attached, and verified that it allows the program to run without throwing an exception.

However, I must stress, I have no idea whether the `correctness` of the program is in tact, or more importantly the correctness of this feature. There didn't appear to be any tests for it that I could find, otherwise I would have borrowed from those original tests to create a regression test.

I think getting some test coverage around this is much needed!

I hope that helps :)

**Comment by JakeGinnivan** [comment]
I think #350 may fix this issue. 

Can you give it a go

```
git remote add jake git@github.com:JakeGinnivan/GitVersion.git
git fetch jake
git checkout jake/pr/dynamic -t
```

@GeertvanHorrik did most of the hard work, and it has a test now covering the dynamic repos feature.

**Comment by SimonCropp** [comment]
@gep13 ok the disk space issue is weird. No idea why it would fail and then succeed immediately after. Perhaps @gbiellem has an idea?

Apart from that I say we call it a "ghost in the machine" and see if it re-appears

**Comment by gep13** [comment]
> Apart from that I say we call it a "ghost in the machine" and see if it re-appears

Sounds good to me :+1:

**Comment by gbiellem** [comment]
I took a look at thet build agent... Plenty of disk space is available ( in excess of 5 GB) so this is very weird...

**Comment by gep13** [comment]
> I took a look at thet build agent... Plenty of disk space is available ( in excess of 5 GB) so this is very weird...

Very strange indeed!

**Comment by dazinator** [comment]
There's a ghost in my PR! :)
By the way pretty sure this PR is now superceded anyway by #350 as @JakeGinnivan mentioned. I am about to give #350 a go now. If it works, i'll close this PR as it shouldn't be needed :)

**Comment by dazinator** [comment]
Superceded by #350 - closing

**Pull request closed without merging**
