### PR TITLE
Review and comment fixes

### PR DESCRIPTION
**Pull request by JakeGinnivan**

### CODE REVIEW

**Comment by orjan** [comment]
I'm aware that develop defaults to ContinuousDelivery but that hasn't been changed by this commit?

-            fixture.AssertFullSemver("1.3.0-unstable.1+3");
+            fixture.AssertFullSemver("1.3.0-unstable.3");

**Comment by orjan** [comment]
I'll guess it would be great if parts of the default configuration was placed in the readme/wiki

    AssemblyVersioningScheme = AssemblyVersioningScheme.MajorMinorPatch;
            TagPrefix = "[vV]";
            VersioningMode = GitVersion.VersioningMode.ContinuousDelivery;
            ContinuousDeploymentFallbackTag = "ci";

            Branches["master"] = new BranchConfig
            {
                Tag = string.Empty,
                Increment = IncrementStrategy.Patch,
                PreventIncrementOfMergedBranchVersion = true
            };
            Branches["release[/-]"] = new BranchConfig { Tag = "beta" };
            Branches["feature[/-]"] = new BranchConfig
            {
                Increment = IncrementStrategy.Inherit,
                Tag = "useBranchName"
            };
            Branches["hotfix[/-]"] = new BranchConfig { Tag = "beta" };
            Branches["support[/-]"] = new BranchConfig
            {
                Tag = string.Empty,
                Increment = IncrementStrategy.Patch,
                PreventIncrementOfMergedBranchVersion = true
            };
            Branches["develop"] = new BranchConfig
            {
                Tag = "unstable",
                Increment = IncrementStrategy.Minor,
                VersioningMode = GitVersion.VersioningMode.ContinuousDeployment
            };
            Branches[@"(pull|pull\-requests|pr)[/-]"] = new BranchConfig
            {
                Tag = "PullRequest",
                TagNumberPattern = @"[/-](?<number>\d+)[-/]",
                Increment = IncrementStrategy.Inherit
            };

**Comment by JakeGinnivan** [comment]
@orjan yeah because the inheirting of module was the wrong way (global overwrote branch) even though develop was continuous deployment it got overred.

https://github.com/ParticularLabs/GitVersion/tree/release/3.0.0#configuration has been updated to say this. Also you can run `/showConfig` to see the effective configuration (defaults with overrides applied).

Is that enough?

**Comment by JakeGinnivan** [comment]
Basically develop should change SemVer *every* commit by default. Other branches only when you tag them

**Comment by orjan** [comment]
It's perfect, release the beast!

On Mon, Feb 16, 2015 at 10:09 PM, Jake Ginnivan <notifications@github.com>
wrote:

> @orjan <https://github.com/orjan> yeah because the inheirting of module
> was the wrong way (global overwrote branch) even though develop was
> continuous deployment it got overred.
>
>
> https://github.com/ParticularLabs/GitVersion/tree/release/3.0.0#configuration
> has been updated to say this. Also you can run /showConfig to see the
> effective configuration (defaults with overrides applied).
>
> Is that enough?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParticularLabs/GitVersion/pull/371#issuecomment-74572768>
> .
>



-- 
Örjan Sjöholm
0704 - 224 284

**Comment by JakeGinnivan** [comment]
Sweet, appreciate the review. Have made a bunch of silly mistakes in 3.0 and these sort of questions have made for a higher quality release.

**Pull request merged**
