### PR TITLE
Alternative refspecs

### PR DESCRIPTION
**Pull request by thefringeninja**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@thefringeninja this looks good. but what tooling r u using to get that format?

**Comment by thefringeninja** [comment]
I just did what the blog post told me :)

On Thu, Feb 5, 2015 at 11:15 PM, Simon Cropp <notifications@github.com>
wrote:

> @thefringeninja <https://github.com/thefringeninja> this looks good. but
> what tooling r u using to get that format?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParticularLabs/GitVersion/pull/361#issuecomment-73141640>
> .
>



-- 
Sent from my regular computer
http://twitter.com/thefringeninja
http://www.thefringeninja.com/

**Comment by gep13** [comment]
> I just did what the blog post told me :)

Which blog post?  What CI system are you using?

**Comment by nulltoken** [comment]
I'm curious too. From a CI perspective, it'd quite strange to actually rely on the tip of the branch rather than on the merge commit. :confused:

**Comment by JakeGinnivan** [comment]
http://blog.jetbrains.com/teamcity/2013/02/automatically-building-pull-requests-from-github-with-teamcity

I told @thefringeninja to make this change, while suggesting he switch to the merge commit instead. I think we should support it

**Comment by SimonCropp** [comment]
no objections here. the change is fairly harmless

**Comment by JakeGinnivan** [comment]
Yeah, it is more from a wtf why is gitversion not detecting my PR and versioning it like it says it should.

**Comment by gep13** [comment]
Ah, I see.  Yip, no objections from me.

**Pull request merged**
